---
role_name_check: 1

dependency:
  name: galaxy
  options:
    requirements-file: molecule/requirements.yml

driver:
  name: docker

platforms:
  - name: nutclient
    image: "geerlingguy/docker-${MOLECULE_OS:-rockylinux8}-ansible:latest"
    command: ${MOLECULE_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true

provisioner:
  name: ansible
